/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MapboxJNI */

#ifndef _Included_MapboxJNI
#define _Included_MapboxJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MapboxJNI
 * Method:    render
 * Signature: (Ljava/lang/String;LMapboxCallback;)V
 */
JNIEXPORT void JNICALL Java_MapboxJNI_render (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
